name: Lint

on:
  push:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: View context attributes
        uses: actions/github-script@v3
        with:
          script: console.log(context)

      - name: View repo
        uses: actions/github-script@v3
        with:
          script: |
            console.log(context.repo);
            console.log(context.repo.owner);
            console.log(context.repo.repo);
      
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const list = await github.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha,
              check_name: "flake8"
            });
            console.log(list);
            
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
        
      - name: Install flake8
        run: pip install flake8

